In [2]:
#
import numpy as np

def union(A, B):
    return np.maximum(A, B)

def intersection(A, B):
    return np.minimum(A, B)

def complement(A):
    return 1 - A

def difference(A, B):
    return np.maximum(A - B, 0)

def cartesian_product(A, B):
    return np.outer(A, B)

def max_min_composition(R1, R2):
    return np.maximum(np.minimum(R1, R2), 0)

A = np.array([0.2, 0.4, 0.7, 0.8])
B = np.array([0.1, 0.8, 0.2, 0.3])

R1 = cartesian_product(A, B)
R2 = cartesian_product(B, A)
result = max_min_composition(R1, R2)

print("Union of A and B:", union(A, B))
print("Intersection of A and B:", intersection(A, B))
print("Complement of A:", complement(A))
print("Difference of A and B:", difference(A, B))
print(f"Cartesian product of A and B:\n{R1}")
print(f"Cartesian product of B and A:\n{R2}")
print(f"Max-min composition of R1 and R2:\n{result}")


Union of A and B: [0.2 0.8 0.7 0.8]
Intersection of A and B: [0.1 0.4 0.2 0.3]
Complement of A: [0.8 0.6 0.3 0.2]
Difference of A and B: [0.1 0.  0.5 0.5]
Cartesian product of A and B:
[[0.02 0.16 0.04 0.06]
 [0.04 0.32 0.08 0.12]
 [0.07 0.56 0.14 0.21]
 [0.08 0.64 0.16 0.24]]
Cartesian product of B and A:
[[0.02 0.04 0.07 0.08]
 [0.16 0.32 0.56 0.64]
 [0.04 0.08 0.14 0.16]
 [0.06 0.12 0.21 0.24]]
Max-min composition of R1 and R2:
[[0.02 0.04 0.04 0.06]
 [0.04 0.32 0.08 0.12]
 [0.04 0.08 0.14 0.16]
 [0.06 0.12 0.16 0.24]]
